### ISSUE TITLE
Bioconda recipe

### ISSUE THREAD

**Issue by mjsteinbaugh** [Teichlab/celltypist#1]
Would it be possible to add celltypst to bioconda? I'm happy to help create a recipe.

**Comment by mjsteinbaugh** [comment]
Awesome I see this in [bioconda-recipes](https://github.com/bioconda/bioconda-recipes/pull/29774). Thanks!

**Comment by prete** [comment]
Hi @mjsteinbaugh, thank you for the offering and sorry we missed this issue. We've already submitted the PR but needs a fix and actually the package should be available once [this PR](https://github.com/bioconda/bioconda-recipes/pull/29783)  is merged.
