### ISSUE TITLE
codes for harmonizing the cell labels

### ISSUE THREAD

**Issue by YOU-k** [Teichlab/celltypist#101]
Thanks for providing this software to use. Just for curious about the details of harmonizing the cell labels, will the code about that and the code to generate the tree plots to be provided later? cheers, Yue

**Comment by ChuanXu1** [comment]
@YOU-k, due to some considerations, we have isolated the harmonization and integration modules into a separate tool [CellHint](https://github.com/Teichlab/cellhint), and now CellTypist will be retained as a cell-type-classification-focused tool.
