### ISSUE TITLE
the question about conf_score

### ISSUE THREAD

**Issue by Xyihang** [Teichlab/celltypist#102]
"Like this, I have completed clustering myself and annotated cell types for the clustering results. Now, I am using celltypist to automate type annotation based on my clustering. I have obtained the following results. So, what does 'conf_score' represent? Does the probability of 0.216800 suggest it's the 'predicted_labels', or is it 'majority_voting'?"
![2023-12-02 140526](https://github.com/Teichlab/celltypist/assets/59789634/ec01f33f-e84c-4447-8e94-876d192169e4)

**Comment by Xyihang** [comment]
I've verified that the findings are predicted_labels and hope to be able to give confidence for each cluster in the future

**Comment by ChuanXu1** [comment]
Will close the issue; please reopen it if you have further questions.
