### ISSUE TITLE
CellTypist_Immune_Reference_v2 question

### ISSUE THREAD

**Issue by NikicaJEa** [Teichlab/celltypist#103]
Hi!
I was playing around with celltypist and wanted to test different training parameters on the most recent reference dataset immune_v2. I saw in your wiki that you have a prepared file (/nfs/team205/cx1/Celltypist/expand_immune/data/CellTypist_Immune_Reference_v2.h5ad) which is unfortunately not publicly available. Therefore I tried to reconstruct the immune_v2 reference dataset by combining the organ atlas datasets.

However, there I encountered a small issue. I noticed that the annotation in Blood.h5ad does not contain the new immune_v2 annotation but probably the outdated version? For example Tgd_CRTAM+ can be found in the label harmonization tree but not in the Curated_annotation slot of Blood.h5ad .

Any help is much appreciated!
Cheers!

**Comment by ChuanXu1** [comment]
@NikicaJEa, the reference data is here https://cog.sanger.ac.uk/celltypist/rm/CellTypist_Immune_Reference_v2_count.h5ad

**Comment by NikicaJEa** [comment]
Thank you so much!

**Comment by sztankatt** [comment]
Hi @ChuanXu1, As a follow-up to this question: what is the reason behind the inconsistency in the `Curated_annotation` cell-labels (in the Blood organ atlas: https://www.celltypist.org/organs) an the Immune v2 dataset labels: https://www.celltypist.org/encyclopedia/Immune/v2 ? For instance Immune v2 has one `Memory B-cell` type, while the blood atlas has two additional types `Non-switched memory B cells` and  `Switched memory B cells`. 

When using the `Adult_Human_Blood.pkl` model, would it make sense to rename the labels (after running celltypist) to match the Immune v2 names?
