### ISSUE TITLE
Running celltypist with concatenated dataset

### ISSUE THREAD

**Issue by malonzm1** [Teichlab/celltypist#106]
Hi,

I have datasets that I need to concatenate. Is it ok to run celltypist after concatenation or should I run it on the individual datasets before concatenation?

Thanks and good day.

Br,

**Comment by ChuanXu1** [comment]
@malonzm1, `predicted_labels` is not impacted, but `majority_voting` will be, due to the over-clustering step (different data structures will result in different clusterings).

**Comment by malonzm1** [comment]
Thanks. Would you say that if I were interested in `majority_voting` it would be better to perform celltypist before concatenation?

**Comment by ChuanXu1** [comment]
@malonzm1, it depends. Usually, cells will be clustered in a better manifold when several datasets are combined and greater resolution is achieved, but sometimes clustering on a single dataset may reveal a better clustering shape (e.g., due to alleviated batch effect or optimal set of HVGs).

**Comment by ChuanXu1** [comment]
Should be resolved. Please reopen the issue if you have further questions.
