### ISSUE TITLE
Can not download the model

### ISSUE THREAD

**Issue by Knight1995** [Teichlab/celltypist#117]
Great jobs! Today I want to download the model, but I fail. And the download link cannot open (https://celltypist.cog.sanger.ac.uk/models/models.json). What is the problem? Many thanks.
![image](https://github.com/Teichlab/celltypist/assets/88174091/76a6a846-5a20-4637-971a-6e177b969d24)

**Comment by ChuanXu1** [comment]
@Knight1995, it works for me. Do you still have the issue?

**Comment by Knight1995** [comment]
Thanks for your reply. It works now. Maybe it was caused by a network error.
