### ISSUE TITLE
sequencing protocol requirements?

### ISSUE THREAD

**Issue by nrosed** [Teichlab/celltypist#12]
This is more of a question than an issue, but do the trained models only work on samples sequenced on a 10x platform, or can we expect it to also work well for smart-seq2?

If we are not using 10x data, can we simply build a new model, or are there some assumptions in the model that would lead to performance differences?

**Comment by ChuanXu1** [comment]
@nrosed , several optimizations are applied during CellTypist model training to accommodate predictions for datasets with different batches/protocols. 10x is preferable, but others (e.g., SS2) should also work well. Please let us know if you find a bad performance in predicting your data.

**Comment by nrosed** [comment]
Thanks for your reply! I didn't notice a performance drop on two SS2 and was surprised, because I thought it would only work for 10x. Happy to know it was intentional in the method design!
