### ISSUE TITLE
Issue accessing www.celltypist.org - 502 Bad Gateway

### ISSUE THREAD

**Issue by lucygarner** [Teichlab/celltypist#120]
Hi,

I am getting the following error when trying to access www.celltypist.org.

![image](https://github.com/Teichlab/celltypist/assets/22564745/1893ce6b-e2ca-4581-90d6-6276d0240452)

Are others having this issue as well?

Best wishes,
Lucy

**Comment by JBollek** [comment]
Indeed, similar issue since I checked yesterday.

Best wishes,

Jacques

**Comment by NicolaasVanRenne** [comment]
same here... :(

**Comment by ChuanXu1** [comment]
We will fix it. In the meantime, you can use the python celltypist package for cell type annotation and this [table](https://github.com/Teichlab/celltypist_wiki/blob/main/atlases/Pan_Immune_CellTypist/v2/encyclopedia/encyclopedia_table.xlsx) for marker inspection.

**Comment by ChuanXu1** [comment]
Resolved now.

**Comment by JBollek** [comment]
Thank you very much.
