### ISSUE TITLE
Organ atlas Citing CellTypist. Automatic cell type harmonization and integr…

### ISSUE THREAD

**Issue by Xyihang** [Teichlab/celltypist#121]
adata.obs['Dataset']
ategories (4, object): ['Dominguez Conde et al. 2022', 'Ren et al. 2021', 'Stephenson et al. 2021', 'Yoshida et al. 2021']

it is hard for me to cite these dataset.
how can i do these more easily?

**Comment by ChuanXu1** [comment]
@Xyihang, you can find relevant information at Table S2 of the paper [here](https://doi.org/10.1016/j.cell.2023.11.026)
