### ISSUE TITLE
Any reason why CellTypist is not part of scverse ecosystem?

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [Teichlab/celltypist#123]
Hey, just a quick question on why CellTypist isn't part of the scverse: https://scverse.org/packages/

I think it would be quite nice to submit CellTypist to further expand the packages in this ecosystem!

**Comment by ChuanXu1** [comment]
@Rafael-Silva-Oliveira, sounds good, will try to incorporate CellTypist into it.

**Comment by Rafael-Silva-Oliveira** [comment]
> @Rafael-Silva-Oliveira, sounds good, will try to incorporate CellTypist into it.

Perfect, thank you! Will be a very nice addition to the ecosystem and promote the usage of CellTypist even more across the community :)
