### ISSUE TITLE
Celltypist showing invalid expression matrix

### ISSUE THREAD

**Issue by aditya-sarkar441** [Teichlab/celltypist#14]
I tried running celltypist on the anndata object and it wqs giving me this error. The data is from a research paper : https://github.com/scCOVID-19/COVIDPBMC/

Error: 

Exception: Invalid expression matrix, expect log1p normalized expression to 10000 counts per cell

Can you please help me out with this?

**Comment by ChuanXu1** [comment]
@aditya-sarkar441, as I downloaded and checked that dataset - please remove the proteome expression in that data, by command such as `adata = adata[:, ~adata.var_names.str.startswith("AB_")]`

**Comment by aditya-sarkar441** [comment]
ok. why do we remove this proteome data ?

I got these cell types : ILC, Tcells, Monocytes, B cells. Why am I not getting NK and subtypes of T cells (CD4T, CD8T) ?

**Comment by ChuanXu1** [comment]
@aditya-sarkar441, the prediction is purely based on gene expression, so proteome data should be removed. There should be subtypes showing up, did you select the right model (for example, Immune_All_Low)?

**Comment by aditya-sarkar441** [comment]
Yeah, I selected Immune_All_High

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by aditya-sarkar441** [comment]
@ChuanXu1 My Postdoc mentor is telling me that celtypist can predict dozens of cell types. I am not sure how to do this. Can you please help me with this ? 

This is the command I'm using : 
pred_cont = celltypist.annotate(nature_cont, model = 'Immune_All_High.pkl', majority_voting = True)

**Comment by ChuanXu1** [comment]
@aditya-sarkar441, as I said, you can choose the "Immune_All_Low.pkl" model instead of "Immune_All_High.pkl"

**Comment by aditya-sarkar441** [comment]
Ok thanks, I'll try this out.
