### ISSUE TITLE
Error : sparse matrix length is ambiguous; use getnnz() or shape[0]

### ISSUE THREAD

**Issue by aditya-sarkar441** [Teichlab/celltypist#16]
The anndata is GSE158055. I passed an anndata into the celltypist and got the above error. What is this error and how do I solve it ?

**Comment by ChuanXu1** [comment]
@aditya-sarkar441, according to the information, it may be caused by an improper input format vs. the model in fetching the sparse matrix shape. Can you show the code you used to generate the anndata from GSE158055?

**Comment by aditya-sarkar441** [comment]
http://covid19.cancer-pku.cn/#/metadata

**Comment by ChuanXu1** [comment]
@aditya-sarkar441 , as I checked there is a raw count matrix in `.raw` of that dataset. You can try to normalize and log1p it to serve as the input for CellTypist, instead of the `.X` which seems to come from scran normalization and which does not fit the requirement of CellTypist.

**Comment by aditya-sarkar441** [comment]
The problem is with the majority voting part. So in the command, if I initialize majority voting as False, then it works fine. But when I assign it to be True, then I get the above error. 

I will try the above method once as well.
