### ISSUE TITLE
Using integrated data

### ISSUE THREAD

**Issue by miltargid** [Teichlab/celltypist#19]
Hi,
Thank you for providing the tool!
I integrate the data with harmony which 'corrects' the PCA embeddings as a means of batch correction.
This corrected PCA is then used for downstream clustering.
If I were to use an integrated batch corrected data, would you suggest to save 'harmony-corrected pca' in the 'X_pca' slot of the adata object, since I see that in some modes the classifier uses PCA embeddings?

Kindly advise,
Thanks and Kind regards,

**Comment by ChuanXu1** [comment]
@miltargid, you can save 'harmony-corrected pca' in the 'X_pca' slot, or alternatively, do over clustering yourself, such as `sc.pp.neighbors(adata, use_rep = 'X_pca_harmony')` and `sc.tl.leiden(adata, key_added='over_clustering', resolution = 15/20/30/..)`, and then do `celltypist.annotate(adata, model='xxx', majority_voting = True, over_clustering = 'over_clustering')`
