### ISSUE TITLE
T compartment without exhausted T cells?

### ISSUE THREAD

**Issue by Zifeng-L** [Teichlab/celltypist#21]
Congratulations on this outstanding job! There is a little doubt in my mind that in your dataset (https://www.science.org/doi/10.1126/science.abl5197) your team detected 101 immune populations without any exhausted T cells. I wonder whether it is needed?

**Comment by ChuanXu1** [comment]
@Zifeng-L, sorry for delay. Seems Dr. Dominguez Conde (first author of the paper) didn't get a chance to look at this issue though I have reminded her in May and June. You could directly contact her at cecilia.dominguez@fht.org

**Comment by Zifeng-L** [comment]
> @Zifeng-L, sorry for delay. Seems Dr. Dominguez Conde (first author of the paper) didn't get a chance to look at this issue though I have reminded her in May and June. You could directly contact her at [cecilia.dominguez@fht.org](mailto:cecilia.dominguez@fht.org)

Thanks for your help! I would contact her directly.
