### ISSUE TITLE
CellTypist with batch correction

### ISSUE THREAD

**Issue by LeonHafner** [Teichlab/celltypist#31]
Hi together,
great tool you have created with CellTypist!
Since I work with mixed scRNA-Seq data from multiple patients, I need to do a batch effects correction before the cell type annotation.
Unfortunately, I don't know of any method that corrects batch effects while leaving the data in a count matrix.
There will always be negative data that does not correspond to a count matrix anymore.
Is it still possible to apply CellTypist after a batch effects correction, although the data is not in 1e4 and log1p format?
Any other ideas to find a workaround for that problem?

Thanks a lot!

**Comment by ChuanXu1** [comment]
@LeonHafner, you can resort to your raw count matrices, concatenate them, perform normalization, and apply CellTypist afterwards.
