### ISSUE TITLE
How to update the model

### ISSUE THREAD

**Issue by hxpGit512** [Teichlab/celltypist#32]
Dear Celltypist Team,

If I have a new annotated dataset, how can I train and update it into the existing model ？

Looking forward to your reply！

**Comment by ChuanXu1** [comment]
@hxpGit512, you can check the [Usage](https://github.com/Teichlab/celltypist#usage) (Supplemental guidance -> generate a custom model) for details on how to train a model and save it into the existing model list. Also check out the [celltypist.train](https://celltypist.readthedocs.io/en/latest/celltypist.train.html) function for the training parameters.

As an example, if you have an AnnData with highly variable genes, you can train the model using `model = celltypist.train(adata[:, adata.var.highly_variable], 'cell_type_column', n_jobs = -1, max_iter = 500, check_expression = False)` followed by `model.write(f"{celltypist.models.models_path}/some_model_name.pkl")`

**Comment by hxpGit512** [comment]
已收件

**Comment by hxpGit512** [comment]
@ChuanXu1 , Multiple annotated datasets can be trained in batches and then incorporated into one model ？

**Comment by ChuanXu1** [comment]
@hxpGit512, do you mean multiple datasets with different annotations? If yes, you need to train and save each of them separately.
