### ISSUE TITLE
Are the confidence scores of celltype predicted by different reference models comparable？

### ISSUE THREAD

**Issue by hxpGit512** [Teichlab/celltypist#35]
Dear Celltypist Team,
       Are the confidence scores of celltype predicted by different reference models comparable? whether I could choose the most suitable  model to annotate new datasets  by comparing the average confidence scores of each cluster annotated by different models?  in addition, If a cell is annotated as “unassigned”or “heterogeneous”, what does its confidence score mean？

**Comment by hxpGit512** [comment]
已收件

**Comment by ChuanXu1** [comment]
I will close the issue as this should be solved. Please let us know if you still have problems.

**Comment by hxpGit512** [comment]
已收件
