### ISSUE TITLE
Details to be added about the available model

### ISSUE THREAD

**Issue by saeedfc** [Teichlab/celltypist#37]
Dear,

In the description of the model it is not clear whether the model involves cells from both healthy and CD or just healthy? I am especially referring to 'Cells_Intestinal_Tract ' from intestinal cells from fetal, pediatric and adult human gut (134 cell types). The original study associated also has CD data. Hence the confusion.

Kindly clarify.

**Comment by ChuanXu1** [comment]
@saeedfc, good point! The 'Cells_Intestinal_Tract' indeed contains pediatric CD cells. Will clarify this in the model details.

**Comment by ChuanXu1** [comment]
@saeedfc, the model details have been updated.

https://www.celltypist.org/models

https://github.com/Teichlab/celltypist_wiki/blob/main/json/models.json#L56

**Comment by ChuanXu1** [comment]
This issue should be solved. Please let me know if you still need more details for the model.
