### ISSUE TITLE
'Naive' cell type in 'Adult_Mouse_Gut' model

### ISSUE THREAD

**Issue by rgranit** [Teichlab/celltypist#42]
What is the meaning of the 'Naive' cell type in 'Adult_Mouse_Gut' model? seems like 'Naive B-cells' ..
![image](https://user-images.githubusercontent.com/9028967/201538805-bed1b598-c4bb-49c4-879f-29931f4f4126.png)

**Comment by ChuanXu1** [comment]
@rgranit, thx for this, will give cell types understandable names in this model in a future version. For your question, this is naive B cells from https://pubmed.ncbi.nlm.nih.gov/35508130/.

**Comment by rgranit** [comment]
@ChuanXu1 great, thanks for your reply..  🙏
