### ISSUE TITLE
Train Custom Model on scATAC-seq data?

### ISSUE THREAD

**Issue by jacklynnewsome** [Teichlab/celltypist#49]
Hello,

Is it at all possible to train a custom celltypist model on scATAC-seq data and then use it for predicting cell types in scATAC-seq datasets? I've been trying accomplish this, but so far it seems incompatible, despite my efforts.

**Comment by ChuanXu1** [comment]
@jacklynnewsome, this should work if you provide the abundance matrix to CellTypist for training. You can detail the error here if it fails

**Comment by ChuanXu1** [comment]
I will close this issue. Please re-open it if you still have problems dealing with this.
