### ISSUE TITLE
Add a ``celltypist.download_model(force_update=True)`` API

### ISSUE THREAD

**Issue by watiss** [Teichlab/celltypist#5]
celltypist has an API `download_models(force_update: bool=False)` to download all models with the latest version. We don't want this for all models, only a handful. Could you provide an API for a single model? Something like ``celltypist.download_model(force_update=True)`` If there is already a way to do this with the current API, please let me know.
Thanks!

**Comment by ChuanXu1** [comment]
A `model` parameter is added in `celltypist.models.download_models`, you can download a single model by  `celltypist.models.download_models(model='Immune_All_Low.pkl', force_update=True)` or `celltypist.models.download_models(model=['Immune_All_Low.pkl'], force_update=True)`, or download multiple models by `celltypist.models.download_models(model=['Immune_All_Low.pkl', 'Immune_All_High.pkl'], force_update=True)`.

This change will be reflected in the next CellTypist version.
