### ISSUE TITLE
Adult_Mouse_Gut cell types 

### ISSUE THREAD

**Issue by ejc043** [Teichlab/celltypist#53]
Hello! Might the team have the publications where the Adult_Mouse_Gut model derived its cell types? It says 'TBD' in the celltypist site.

**Comment by ChuanXu1** [comment]
@ejc043, the preprint is here https://www.biorxiv.org/content/10.1101/2022.08.26.505428v2. I will add the link to the model soon.

**Comment by ejc043** [comment]
@ChuanXu1 Thanks!

**Comment by ejc043** [comment]
Hi @ChuanXu1 , 
there are some celltypes where the preprint you've linked does not reference e.g. glia cells 
Do you know if there is a separate publication where those celltype annotations were derived from?
Thank you again,
Eunice

**Comment by ChuanXu1** [comment]
@ejc043 , table here [](url)
[stats_mouse_gut.xlsx](https://github.com/Teichlab/celltypist/files/10420586/stats_mouse_gut.xlsx)

**Comment by ejc043** [comment]
@ChuanXu1 This is great thank you so much!!

**Comment by Lucyyang1991** [comment]
How can I download the processed data used to train the `Adult_Mouse_Gut.pkl` model? In fact, many models need to be subsetted and retrained, but it's really difficult to find this processed data the model from. Do you plan to organize and release the processed dataset?

**Comment by ChuanXu1** [comment]
@Lucyyang1991, nearly all datasets are available for download from the original publications, and no additional processing was performed for most of the CellTypist training.
