### ISSUE TITLE
NK cells vs CD16+/ CD16- cells

### ISSUE THREAD

**Issue by kate-simonova** [Teichlab/celltypist#59]
I would like to thank you for this amazing tool as first. Then  I would like to ask on subpopulation of NK cells in v2 Immune panel. What are the differences between NK cells and other cell populations (CD16+/ CD16- cells, cycling NK cells)? Was it just like that the tool was not able to identify which exactly this population is? Or is it a separate population with specific function? It was not that clear from the Atlas.

Kind regards,

K.

**Comment by kate-simonova** [comment]
I will probably also mention that I looked at majority voting column.

**Comment by ChuanXu1** [comment]
@kate-simonova, the natural killer cells in our immune reference data are assigned two categories (CD16+, CD16-), with the remaining unassigned natural killer cells collectively referred to as "NK cells". Hope it's clear.
