### ISSUE TITLE
Input with 10x matrix containing Antibody Capture

### ISSUE THREAD

**Issue by ollieeknight** [Teichlab/celltypist#62]
Heya,

I'm getting an error that the feature names don't match, from a 10x 5' run where gene expression and cite-seq are counted together. I'm using it through the command line, like:
```
celltypist --transpose-input --indata outs/filtered_feature_bc_matrix/matrix.mtx.gz --model Immune_All_Low.pkl --outdir celltypist/ -gf outs/filtered_feature_bc_matrix/features.tsv.gz -cf outs/filtered_feature_bc_matrix/barcodes.tsv.gz
```

I'm wondering if the features don't match because the .mtx file has two entries, Gene Expression and Antibody Capture. Is there a way to subset the input so that only the first matrix (Gene Expression) is chosen?

Thanks!

Ollie

**Comment by ChuanXu1** [comment]
@ollieeknight, does your features.tsv file contain two columns? It is supposed to only have one feature column (without header).

**Comment by ollieeknight** [comment]
thanks for getting back to me - it has three columns (ensemble ID, gene name, matrix present): [features1.csv](https://github.com/Teichlab/celltypist/files/11381879/features1.csv). I had to convert it to a csv to upload it here, but it was originally a .tsv.gz file.

**Comment by ChuanXu1** [comment]
@ollieeknight, you may need to manually delete the first and third columns to get a new table as the feature input file.

**Comment by ollieeknight** [comment]
no worries, thanks for letting me know. this is just a standard 10x cellranger count output, so might it be worth adding this functionality in the future? Just a thought. Appreciate your help!
