### ISSUE TITLE
Training data for Immune_All_Low

### ISSUE THREAD

**Issue by MichaelLauber** [Teichlab/celltypist#63]
Hey guys,

I saw that the Immune_All_Low model contains both "broad" and "detailed" cell types for example 'ILC' and 'ILC precursor', 'ILC1', 'ILC2', 'ILC3' or "B cells" and 'Naive B cells', 
'Pre-pro-B cells', 'Pro-B cells', 'Proliferative germinal center B cells' etc.

What are the broad cell types composed of? 
Are they an aggregation of the "detailed" cell types or were these cells that could not be labeled to a finer level or something else?

**Comment by ChuanXu1** [comment]
Will close this, please reopen it if you have further question.
