### ISSUE TITLE
Harmonizing datasets with missing annotations

### ISSUE THREAD

**Issue by pakiessling** [Teichlab/celltypist#64]
Thank you for the tool. It looks exactly like something I need.

I have a multiple datasets of a specific celltype where some of the datasets where subclustered and annotated and others not.

Can I run celltypist harmonization on all of them and it will try to label the unlabeled cells with existing harmonized labels or do I need to harmonize the existing annotation first and then run celltypist classification with the harmonized labeled set as reference?

**Comment by ChuanXu1** [comment]
@pakiessling, thank you for using CellTypist!

You have to collect annotation for each dataset, and CellTypist will try to harmonise/align their annotations. After harmonisation, the `alignment.reannotation` will contain harmonised cell types in the `reannotation` and `group` column, which can be used for reference. In short, each dataset needs to have annotation (if you do not have such information, you can perform clustering for the dataset with missing annotation, and use its clustering numbers as an alternative).

Also please use the latest version of CellTypist (1.5.0).
