### ISSUE TITLE
type error when the input is Anndata

### ISSUE THREAD

**Issue by jjxia955** [Teichlab/celltypist#65]
See attached photos
![image](https://github.com/Teichlab/celltypist/assets/117483585/6665b491-3ef7-4ba4-9247-8945f7c587be)

![image](https://github.com/Teichlab/celltypist/assets/117483585/a6f0924e-7621-4fd9-b19b-411407244ff1)

my adata is like this
![image](https://github.com/Teichlab/celltypist/assets/117483585/67e7e0ba-d61c-4a23-8d2e-9f25e80d6d57)

Thanks for help!

**Comment by ChuanXu1** [comment]
@jjxia955, can you show the full traceback error?

**Comment by jjxia955** [comment]
![image](https://github.com/Teichlab/celltypist/assets/117483585/8a42b5f1-c750-4e0b-9f8d-930c70ef2189)
![image](https://github.com/Teichlab/celltypist/assets/117483585/f2255548-2483-4169-a17e-1695ce034a8d)
Here you go!

**Comment by ChuanXu1** [comment]
@jjxia955, installing a new version of CellTypist will solve this.

**Comment by hanjun98** [comment]
Hi, I recently downloaded it from bioconda, but I got this error, so I re-downloaded it from pip and ran it, but the same error comes up.
What should I do?

**Comment by ChuanXu1** [comment]
@hanjun98, could you confirm your version by `celltypist.__version__`?

**Comment by hanjun98** [comment]
yeap! I cofirmed my version, so I knew my celltypist version is 0.1.9
but I want to update celltypist to latest version, requirements pkg, 'annoy' have so many collision with pkgs in my conda env. 
Do you know how long I have to wait for this? Or any way to install?

**Comment by ChuanXu1** [comment]
@hanjun98, sorry for late reply. The new version (1.6.0) has no dependency on annoy any more.

**Comment by ChuanXu1** [comment]
This should be solved. Please reopen it if you have further questions.
