### ISSUE TITLE
download_models corrupts models.json when the server is unavailable

### ISSUE THREAD

**Issue by itamarb-cgen** [Teichlab/celltypist#67]
Hi,
If force_update=True in models.download_models and the server is unavailable (see error message below) - the function corrupts .celltypist/data/models/models.json and cellTypist cannot work on the previously downloaded models. 

Error message:
Exception: 🛑 Cannot fetch 'https://celltypist.cog.sanger.ac.uk/models/models.json', the error is: 503 Server Error: Service Unavailable for url: https://celltypist.cog.sanger.ac.uk/models/models.json 

Thanks,
Itamar

**Comment by prete** [comment]
Hi @itamarb-cgen, thanky for using CellTypist. I'm so sorry that the service is not working right now. The server that hosts the models is currently having problems serving files. We're aware of the issue and our infrastructuree team is working hard to resolve it as quickly as possible.
