### ISSUE TITLE
Issue with downloading models: 503 Server Error

### ISSUE THREAD

**Issue by jkbenotmane** [Teichlab/celltypist#68]
Hello @celltypist-devs,

First, I would like to thank you for your work on celltypist. The tool is incredibly valuable and helpful in our research.

I recently encountered an issue when attempting to download models using the following code:

```python
from celltypist import models
models.download_models(force_update = True)
models.models_description()
```

When running the above, I get the following exception:

```python
Exception: 🛑 Cannot fetch 'https://celltypist.cog.sanger.ac.uk/models/models.json', the error is: 503 Server Error: Service Unavailable for url: https://celltypist.cog.sanger.ac.uk/models/models.json
```

This suggests that the server is currently unavailable, possibly due to maintenance or unexpected downtime. I attempted this at different times to rule out temporary server issues, but the problem persists. 

I thought it best to bring this to your attention, in case there might be an issue with the server or the model hosting. Could you please look into this issue and provide some guidance on how it can be resolved? I'm sure many users would benefit from a fix or a workaround.

Thank you in advance for your assistance and for your continued work on celltypist.

Best Regards,

Jasim

**Comment by prete** [comment]
Hi @jkbenotmane as mentioned in #66 and #67. The server that hosts the models is currently having problems serving files. We're aware of the issue and our infrastructure team is working hard to resolve it as quickly as possible. The issues started late last night (UK time) and [hopefully] be solved during the course of the evening. 

Thank you for bearing with us!

**Comment by jkbenotmane** [comment]
Thank you very much for the prompt response and your endeavours to solve the issue. 

Another critic would be, that celltypist almost always fails with :

```
ValueError: 🛑 Invalid expression matrix, expect log1p normalized expression to 10000 counts per cell
```
Making it hard to debug at times.

**Comment by ChuanXu1** [comment]
@jkbenotmane, this error has been turned into a warning since version 1.2.0.

By the way, the information indicates that you need to provide a normalized expression, such as those derived by `sc.pp.normalize_total(adata, target_sum = 1e4)` and `sc.pp.log1p(adata)` if you start with the raw count matrix containing all genes.

**Comment by jkbenotmane** [comment]
@ChuanXu1  Thank you for coming back to me, I reinstalled celltypist with pip and performed log1p normalization **after** scVi 1e4 normalization and it solved my issue ...
Thank you for curing my stupidity!
