### ISSUE TITLE
reannotation returns many "UNASSIGNED" cells

### ISSUE THREAD

**Issue by YawnC** [Teichlab/celltypist#71]
Hi there, I have run into an issue in dataset integration. 
I used celltypist.harmonize to merge the datasets which were pre-annotated under low-hierarchy. the reannotation result turned to have around 1/3 cells annotated as "UNASSIGNED". Then I tired to annotate each dataset under high-hierarchy, which is like 5-6 basic cell-types per dataset, the "UNASSIGNED“ cells decreased, but still take about 20% of total cells. All these "UNASSIGNED" cells were assigned into certain groups. I wonder whether this is normal, or is there any solutions to further decrease the number of "UNASSIGNED" cells?
BTW, thanks for such wonderful tool!

**Comment by ChuanXu1** [comment]
@YawnC, you can try the new version (1.5.1 or 1.5.2), which will have fewer UNASSIGNED cells due to an refined reannotation strategy.

**Comment by YawnC** [comment]
Great! The new version worked with no UNASSIGNED provided! Thanks!
