### ISSUE TITLE
T helper cells

### ISSUE THREAD

**Issue by SirKuikka** [Teichlab/celltypist#72]
Hi,

I wonder why celltypist can only predict Type 1 helper T cells and Type 17 T helper cells but not Type 2.

And what is your feeling about annotation 
of helper T cell subtypes? Is it generally difficult to distinguish their subtypes in scrnaseq-data?

**Comment by cc36** [comment]
Hi,

I think that this is because the Th2 were not as abundant in our training sets as Th1 and Th17.
