### ISSUE TITLE
`ImportError` with `sklearn==1.3.0`

### ISSUE THREAD

**Issue by sunnyosun** [Teichlab/celltypist#73]
Hello,

It seems there's some renaming in sklearn 1.3.0 which is no longer compatible with celltypist:

<img width="977" alt="Screenshot 2023-06-30 at 13 27 32" src="https://github.com/Teichlab/celltypist/assets/38218185/5dfc21f2-028e-4bbf-b424-ebbffd171b60">

**Comment by ChuanXu1** [comment]
Thank you for pointing out this, will fix this soon

**Comment by bbimber** [comment]
@ChuanXu1: thanks for this fix. we are seeing this too. Do you plan to push a release?

**Comment by ChuanXu1** [comment]
@bbimber, new version has been published (1.5.3).
