### ISSUE TITLE
Harmonize and Integrate

### ISSUE THREAD

**Issue by YawnC** [Teichlab/celltypist#88]
Hi, just upgraded to 1.6.1, it seems the harmonize and integrate function were removed, is that true? how about the tree-plot function?
<img width="382" alt="image" src="https://github.com/Teichlab/celltypist/assets/118878017/e1e2b3ea-c803-4b78-bdb4-710933765058">
<img width="388" alt="image" src="https://github.com/Teichlab/celltypist/assets/118878017/7092fab0-7bc5-403f-ad8d-4aad87c5f77a">

**Comment by ChuanXu1** [comment]
@YawnC, due to some considerations, we have isolated the harmonization and integration modules into a separate tool [CellHint](https://github.com/Teichlab/cellhint), and now CellTypist will be retained as a cell-type-classification-focused tool.
