### ISSUE TITLE
Wording on message

### ISSUE THREAD

**Issue by bbimber** [Teichlab/celltypist#9]
This is a minor point, but the current code logs this:

logger.info("👀 Can not detect a neighborhood graph, construct one before the over-clustering")

when the input data lacks a neighborhood graph. It seems like celltypist automatically creates one in this situation. I would suggest re-phrasing that message more like:

logger.info("👀 Can not detect a neighborhood graph, will construct one before the over-clustering")

to make it clear celltypist is fixing this. the phrasing "construct one before the over-clustering" sounds more like the tool is asking the user to construct one before running celltypist.

**Comment by ChuanXu1** [comment]
Exactly! Thank you so much! Fixed now a12c715fd9e60a06819c448305188f91c7232beb
