### ISSUE TITLE
confidence score definition

### ISSUE THREAD

**Issue by mjstrumillo** [Teichlab/celltypist#91]
Hi, I'm sorry if it's mentioned somewhere, but I checked both suppl and the online docs - how is the confidence score exactly defined?

**Comment by ChuanXu1** [comment]
@mjstrumillo, this is the probability from logistic regression (i.e., linear combination of gene expression and weights -> decision score -> softmax transformation -> probability)

**Comment by ChuanXu1** [comment]
I will close this issue. Please do let me know if you have further questions.
