### ISSUE TITLE
Use of metacells?

### ISSUE THREAD

**Issue by andreahanel** [Teichlab/celltypist#97]
Hello,
Do you see it as possible to use metacells (created by e.g. SEACells or MetaCell) to potentially improve annotation performance? I understand if direct use of metacells is suboptimal for a classifier trained on single cells; though could be the information about the metacells assignment of each cell be introduced into the majority-voting step? Thank you!

**Comment by ChuanXu1** [comment]
@andreahanel, regarding `the metacells assignment of each cell`, do you mean a hard assignment or a probability assignment. For the former, you can treat each metacell as a cell type in a broad sense during CellTypist training. For the latter, I am afraid the current algorithm does not take this into account (i.e., each cell only has one unique identity). Please let me know if I misunderstand your question.

**Comment by YH-Zheng** [comment]
@ChuanXu1 Do you mean, can I use the results of SEACell (merged Metacell matrix with cell type annotations) as input for celltypist reference set training? 
Now I have a very large scRNA dataset that I want to use as a reference. I have used SEACell to calculate metacells according to each celltypes. Should I use single-cell downsampled data as the input for training or metacells?

**Comment by ChuanXu1** [comment]
@YH-Zheng, theoretically you need a cell-by-gene matrix for model training, with each cell annotated as cell type or meta cell type.

**Comment by ChuanXu1** [comment]
This should be answered. Please reopen this issue if you have further questions.
